### PR TITLE
    NGINX Plus separate installation of Linux and FreeBSD

### PR DESCRIPTION
**Pull request by vbotka**
* Added variable nginx_plus_linux_families: ['Alpine', 'Debian',
      'RedHat', 'Suse']
    * Added variable nginx_plus_bsd_systems: ['FreeBSD']
    * Added variable nginx_freebsd_extra_packages: ['security/ca_root_nss']
    * Installation of Linux moved to install-plus-linux.yml
    * Installation of FreeBSD moved to install-plus-bsd.yml
    * Installation of nginx_freebsd_extra_packages moved to
      tasks/prerequisites/setup-freebsd.yml
    * Installation of NGINX Plus tested with FreeBSD 12.0; Lint passed

### CODE REVIEW

**Comment by vbotka** [comment]
Do the *nginx-plus* packages have any versions? I've left the option `` nginx_version | default('')`` in the code. Is this OK?

```
    - name: "(Install: FreeBSD) Install nginx-plus{{ nginx_version | default('') }}"
￼      pkgng:
￼        name: "nginx-plus{{ nginx_version | default('') }}"
```

**Comment by vbotka** [comment]
Notes:
- Installation of Linux by module *package*
- Installation of Freebsd by module *pkgng*
- Installation of *nginx_freebsd_extra_packages: ['security/ca_root_nss']* moved to *prerequisities*

**Comment by alessfg** [comment]
Couple questions:
1. Is there any reason to switch from `package` to `pkgng` besides the latter being a more featured module?
2. Is `security/ca_root_nss` a required dependency? If so, maybe it'd be best to hardcode it into `prerequisites/setup-freebsd.yml`? And if it's only a required dependency maybe it could live in `plus/install-plus-bsd.yml`? (Don't have a set opinion on this, but I'd like to hear your thoughts).

Another thought, maybe it'd be best to merge everything in `plus/setup-freebsd.yml` to `install-plus-bsd.yml`? Seems a bit redundant to have two different files with only a couple tasks in each.

**Comment by vbotka** [comment]
> 1. Is there any reason to switch from `package` to `pkgng` besides the latter being a more featured module?

No. There isn't any other reason. I automatically use `pkgng` in FreeBSD to preserve the specific options.  I do not insist on the module `pkgng`. Feel free to replace it with `package`. In the end, my understanding is that `package` internally uses `pkgng`.

> 2. Is `security/ca_root_nss` a required dependency? If so, maybe it'd be best to hardcode it into `prerequisites/setup-freebsd.yml`? And if it's only a required dependency maybe it could live in `plus/install-plus-bsd.yml`? (Don't have a set opinion on this, but I'd like to hear your thoughts).

Yes. `security/ca_root_nss` is a required dependency. It's the bundle of the CA root certificates necessary to verify any certificate. It should be part of any base system that wants to connect to the Internet. 

Yes. `prerequisites/setup-freebsd.yml` is the right place. Instead of hardcoding, I decided to put it into the variable `nginx_freebsd_extra_packages`. I recommend to keep it configurable.  See for example https://wiki.freebsd.org/OpenSSL. Installation from ports would need `openssl` from ports as well.

But also here I do not insist on `prerequisites/setup-freebsd.yml`. Frankly, I think it's the same case as `sanity` before. Such basic installation might be done outside the role. It's up to you to keep it, or not. Feel free to reject it.

> Another thought, maybe it'd be best to merge everything in `plus/setup-freebsd.yml` to `install-plus-bsd.yml`? Seems a bit redundant to have two different files with only a couple tasks in each.

I don't think so. The prerequisites is the common place for other installations (oss, plus, modules, ...). I agree the fragmentation might seem excessive.

**Comment by alessfg** [comment]
Thanks for sharing your thoughts! Re 
>I don't think so. The prerequisites is the common place for other installations (oss, plus, modules, ...). I agree the fragmentation might seem excessive.

I think you might have misunderstood me. I meant the `plus/setup-freebsd.yml` and `plus/install-plus-bsd.yml` files, not the prerequisite files. I think that if there's going to be an `install-plus-bsd.yml` file it would make sense to configure the NGINX Plus repository in the same file.

**Comment by vbotka** [comment]
> I think you might have misunderstood me. I meant the `plus/setup-freebsd.yml` and `plus/install-plus-bsd.yml` files, not the prerequisite files. I think that if there's going to be an `install-plus-bsd.yml` file it would make sense to configure the NGINX Plus repository in the same file.

Yes, I did. You're right. I've merged plus/setup-freebsd.yml into the file `plus/install-plus-bsd.yml`. Works fine with FreeBSD 12.0.

**Comment by vbotka** [comment]
@alessfg, I have couple of questions.

1) Is the restriction  `min_ansible_version: 2.4.0.0` current?
2) Is there any roadmap/plan on how Ansible will be upgraded?
3) Is it OK to use `loop` instead of `with_*`?

Some facts:

- Reviewing the code I realized that I had used `loop` in `tasks/prerequisites/setup-freebsd.yml` and nobody complained.
```
loop: "{{ nginx_freebsd_extra_packages }}"
```
- [loop](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#loops) was added in Ansible 2.5

- The role's meta says `min_ansible_version: 2.4.0.0`

**Comment by alessfg** [comment]
> 1. Is the restriction min_ansible_version: 2.4.0.0 current?

No, the restriction on Ansible is not necessarily current. Last time I made some breaking changes Ansible 2.4 had just released and I updated the metadata version respectively. That being said, it should at least be updated to the least supported version at the moment.

> 2. Is there any roadmap/plan on how Ansible will be upgraded?

Not at the moment, but there definitely should be. My main idea on how to do this would be to hardcode the minimum Ansible version in travis, which should ensure that any new changes work on that minimum version. Ideally, I think it'd be good to follow the official Ansible version support guidelines (https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) and make sure the role works with the latest three Ansible releases. That being said, I'm open to suggestions.

> 3. Is it OK to use loop instead of with_*?
 
Definitively. 2.4 came out a long time ago and we're at 2.9 at the moment. Following from my second answer, I'd say it's fair game to update implement any feature that came before 2.7.

It may be a good idea to open a separate issue to track this.

**Pull request merged**
