### PR TITLE
Add IP Restriction for web servers

### PR DESCRIPTION
**Pull request by clwluvw**
### Proposed changes
Add ip restriction with `allow` and `deny` to web servers

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

-   [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx/blob/master/CONTRIBUTING.md) document
-   [x] I have added Molecule tests that prove my fix is effective or that my feature works
-   [x] I have checked that all Molecule tests pass after adding my changes
-   [x] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)

### CODE REVIEW

**Comment by clwluvw** [comment]
@alessfg two of the jobs has been timeout. Can you please run them again?

**Comment by alessfg** [comment]
Done, but the tests seems to be failing as detailed in https://github.com/nginxinc/ansible-role-nginx/pull/302#issuecomment-671537381

**Comment by alessfg** [comment]
Hey @clwluvw! I managed to fix the failing tests while wrapping up the latest release. That being said, could you resubmit this PR here https://github.com/nginxinc/ansible-role-nginx-config? Starting from the latest release, 0.15.0, config related issues/PRs should live in the aforementioned repo.

**Comment by clwluvw** [comment]
Closing in favor of https://github.com/nginxinc/ansible-role-nginx-config/pull/10

**Pull request closed without merging**
