### PR TITLE
Fix module installation when with plus

### PR DESCRIPTION
**Pull request by fr6nco**
The default option nginx_delete_licenses is set to true, which causes of removing the license key from the /etc/ssl/nginx folder. 

If modules are set to be installed, the modules are not installed, as the license is removed prior to the module installation.

This pull request triggers a handler, which runs at the end of the playbook. If the variable is set to true, the licenses are removed.

### CODE REVIEW

**Comment by alessfg** [comment]
First of all, thanks for your PR @fr6nco! And thanks for identifying this unintended behavior. 

So, I've had a look at the changes you've made, and I am not a big fan of using `changed_when: true`. Installing NGINX Plus is not idempotent at the moment, but it's something I'd like to try to fix in the future. Setting `changed_when` to true will make it harder to do so.

In theory, if you use the role to provision a new instance, we could get easily rid of that parameter and the handler would still trigger correctly the first time around. Another option would be to modify the order of tasks such that the license will only be deleted after modules have been installed.

What do you think?

**Comment by fr6nco** [comment]
Hi @alessfg,
In this case I would go with re-ordering the tasks. I set the changed_when to true, because if the machine was provisioned with nginx_delete_license = false first, then this line was modified to true, the license was not deleted, which is also unintended.

**Comment by alessfg** [comment]
Yeah in the end the whole delete license path needs some refactoring in general to improve its functionality. Feel free to give it a try if you want. Otherwise, do you think you could make some changes to reorder the tasks as discussed?

**Comment by fr6nco** [comment]
I can try, but earliest somewhere next week.

**Comment by alessfg** [comment]
Any updates on this @fr6nco?

**Comment by fr6nco** [comment]
Hi, sorry was busy lately, but yeah, it ended up being a relatively quick fix. 
Check out the latest commit @alessfg .
Tomas

**Comment by alessfg** [comment]
That works. Thanks @fr6nco 😄

**Pull request merged**
