### PR TITLE
Add custom logrotate config

### PR DESCRIPTION
**Pull request by clwluvw**
### Proposed changes
Closes: #250

### Checklist
-   [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx/blob/master/CONTRIBUTING.md) document
-   [x] I have added Molecule tests that prove my fix is effective or that my feature works
-   [x] I have checked that all unit tests pass after adding my changes
-   [x] If required, I have updated necessary documentation (`defaults/main/` and `README.md`)

### CODE REVIEW

**Comment by clwluvw** [comment]
@alessfg Are these test failures related to my changes? It seems there is a problem with `nginx.conf`

**Comment by alessfg** [comment]
They are related to your changes (tests on master are passing), but I can't quite place where the issue is 🤔

**Comment by clwluvw** [comment]
> They are related to your changes (tests on master are passing), but I can't quite place where the issue is

I have just run logrotate on Alpine and CentOS in tests and it gets failed because there is some problems in `nginx.conf` but I don't change anything in `nginx.conf`!

**Comment by alessfg** [comment]
There's a bunch of warning messages, but those won't make the build fail. The actual error seems to be `error: error running shared postrotate script for '/var/log/nginx/*.log`.

**Comment by clwluvw** [comment]
> There's a bunch of warning messages, but those won't make the build fail. The actual error seems to be `error: error running shared postrotate script for '/var/log/nginx/*.log`.

@alessfg I think it's because of:
```
[error] invalid PID number \"\" in \"/var/run/nginx.pid\"\nerror
```

**Comment by alessfg** [comment]
That could be related, yeah. Maybe when logrotate tries to run it can't read the NGINX PID? If you run the PR against an Alpine/CentOS(or RHEL) VM does it work (besides the warning messages)? If it works then it could be an issue related to the Docker images for Alpine/CentOS.

**Comment by clwluvw** [comment]
> That could be related, yeah. Maybe when logrotate tries to run it can't read the NGINX PID? If you run the PR against an Alpine/CentOS(or RHEL) VM does it work (besides the warning messages)? If it works then it could be an issue related to the Docker images for Alpine/CentOS.

I'm not enough familiar with Apline/CentOS and I don't know whats going wrong. Do you have any idea about it?

**Comment by alessfg** [comment]
I'm trying to debug it on my end but it might take some time before I find a solution. Looks like the issue is indeed caused by a PID error, but everything works fine on master, so something in this PR must have messed up NGINX's PID in Alpine and CentOS.

**Comment by magicalyak** [comment]
The changes above should resolve the issues and pass the tests.  The nginx service isn't running yet, so no pid is there...and thus the error.

**Comment by clwluvw** [comment]
Works fine

**Comment by alessfg** [comment]
I added a task to use `flush_handlers` instead of booting the NGINX service via the logrotate config. I'll merge the PR if tests pass 😄

**Pull request merged**
