### PR TITLE
Added support for try_files

### PR DESCRIPTION
**Pull request by magicalyak**
Added config option to defaults under reverse_proxy locations and modified the default.conf.j2 to support this.
https://github.com/nginxinc/ansible-role-nginx/issues/115

### CODE REVIEW

**Comment by trusche** [comment]
Hi @magicalyak, I can't get this to work, but I may just not quite know what I'm doing :) 

What I want to achieve is this configuration:

```
  location / {
    try_files $uri/index.html $uri @app;
  }

  location @app {
    proxy_pass http://staging_app;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }
```

For background, this is for a Rails app, the location directive is to try serving static assets directly, and passing all other requests along to the Rails server (puma) via the reverse proxy.

With this PR, it seems the `try_files` directive is only supported within the reverse proxy itself (which works fine btw), but not in a regular location directive or on the server level?

**Comment by magicalyak** [comment]
I can add that soon.

**Comment by magicalyak** [comment]
@trusche can you try with the new changes, it should work in the other locations.  Your feedback helps immensely btw.

**Comment by trusche** [comment]
Works in both contexts. One minor quirk is that it's indented too much on the server level:

```
server {
    listen 80;
    server_name localhost;
    root /var/www/vhosts/launchpad/current/public;
        try_files $uri/index.html $uri @app;
    location @app {
        proxy_pass http://staging_app;

```

Thanks again!

**Comment by magicalyak** [comment]
This last push should be the final one (aside from the travis stuff)
@trusche can you double check the indent for me with the latest push?

**Comment by magicalyak** [comment]
Last push was for fixing failing travis tests (i'm being lazy and doing both issues in this PR)
I think that should be it as long as it comes back green.

**Comment by trusche** [comment]
@magicalyak indentation fix confirmed.

**Pull request merged**
