### PR TITLE
Improve config cleanup tasks

### LINKED ISSUE #136: Cannot find mime.types on FreeBSD (cleanup config task removes all files in specified path)
Hello,
I cannot seem to find mime.types (referred by main nginx.conf.j2) 
when using this role to install on FreeBSD 12.

my role code is:

```
---
# I have to set nginxconfigdir__root to /usr/local/etc/nginx on FreeBSD (on lnx it is /etc/nginx)
# (also will need to modify default template, because it hardcodes the pass to linux default, and does nto work on freebsd
# 
- name: install nginx | restapi
  include_role:
    name: nginxinc.nginx
    apply: 
      become: yes
  vars:
    nginx_type: opensource
    # this role has a problem installing modules for fbsd or obsd.
    # disable for now
#    nginx_modules:
#      image_filter: true
#      geoip: true
        
    # Remove previously existing NGINX configuration files.
    nginx_cleanup_config: true
    nginx_cleanup_config_path:
      - "{{ nginxconfigdir__root }}/config.d"  

    nginx_main_template_enable: true
    nginx_main_template:
      template_file: nginx.conf.j2 
      conf_file_name: nginx.conf
      conf_file_location: "{{ nginxconfigdir__root }}"  # I have to set it to /usr/local/etc/nginx on FreeBSD (on lnx it is /etc/nginx)
      user: nginx
      worker_processes: auto
      error_level: warn
      worker_connections: 1024
      http_enable: true
      http_settings:
        keepalive_timeout: 65
        cache: false
        rate_limit: false
        keyval: false
      stream_enable: true
      http_global_autoindex: false


    nginx_stream_template_enable: true
    nginx_stream_template:
      default:  
        template_file:  stream/default.conf.j2
        conf_file_name: restapi__beX.conf
        conf_file_location: "{{ nginxconfigdir__root }}/conf.d/stream"
        network_streams:
          default:
            listen_address: localhost
            listen_port: 4998
            udp_enable: false
            proxy_pass: mybackend
            proxy_timeout: 3s
            proxy_connect_timeout: 1s
            proxy_protocol: false
            health_check_plus: false
            proxy_ssl: 
              cert: "{{ currdomainCertDir }}/{{ certfile__fullchain }}"
              key: "{{ currdomainCertDir }}/{{ certfile__privkey }}"
              password_file: "{{ currdomainCertDir }}/{{ certfile__pass }}"
              protocols: TLSv1 TLSv1.1 TLSv1.2 TLSv1.3
              ciphers: HIGH:!aNULL:!MD5
              verify: false
              verify_depth: 1
              session_reuse: true  
              
        upstreams:
          upstream1: 
            name: mybackend
            zone_name: mybackend
            lb_method: least_conn
            sticky_cookie: false
            zone_size: 64k
            servers:
              server1:
                address: 10.0.1.99
                port: 77777
                weight: 1
                healthcheck: max_fails=2 fail_timeout=10s
              server2:
                address: 10.0.1.999
                port: 88888
                weight: 1
                healthcheck: max_fails=2 fail_timeout=10s

```

### PR DESCRIPTION
**Pull request by alessfg**
### Proposed changes
Previously, all files found in the path specified in `nginx_cleanup_config_path` were deleted. Now, only *.conf files are deleted, and you can specify whether you want to recurse through the paths specified or not. Partially fixes #136.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

-   [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx/blob/master/CONTRIBUTING.md) document
-   [x] If necessary, I have added Molecule tests that prove my fix is effective or that my feature works
-   [x] I have checked that all unit tests pass after adding my changes
-   [x] If required, I have updated necessary documentation (`defaults/main/` and `README.md`)

### CODE REVIEW

**Comment by damex** [comment]
hi, I see that previously you could do something like this in 0.14.0:
```
nginx_cleanup_config: true
nginx_cleanup_config_path:
  - /etc/nginx/conf.d/default.conf
```

removing 'default.conf' which is bundled with nginx 'by default'.
but after this commit (it is in master) such functionality is lost and you can only remove whole directories.

is there a recommended workaround for this or expected to be fixed?

**Comment by alessfg** [comment]
Arguably, that was never the intended functionality, but I see your point. FWIW, if you only want to remove the `default.conf` bundled by default with `nginx`, you could simply include something like
```yaml
nginx_cleanup_config_path:
  - directory:
      - /etc/nginx/conf.d
    recurse: false
```
and that would do the trick.

**Comment by damex** [comment]
it does have completely different behavior with code above when you have default.conf and some other configuration there:

1. it removes all files in directory (not only default.conf, all *.conf files in a directory)
2. ensures configuration that is defined in inventory (triggers 'changed' since files will be considered new)

what is bad about it? it always do hard changes and trigger 'changed' status.

**Comment by alessfg** [comment]
Hm yeah, I can see how for some use cases it might not be an ideal workflow. I'll add an option to delete specific files.

**Comment by alessfg** [comment]
@damex check this PR merged a little bit ago https://github.com/nginxinc/ansible-role-nginx/pull/291

**Comment by damex** [comment]
previous behavior is back although now I need to override default paths array by ```nginx_cleanup_config_paths: []``` in inventory.

```
nginx_cleanup_config: true
nginx_cleanup_config_paths: []
nginx_cleanup_config_files:
  - /etc/nginx/conf.d/default.conf
```

seem to work now like it was working before, thanks.

**Pull request merged**
