### PR TITLE
Add events_custom_options to template.yml defaults

### PR DESCRIPTION
**Pull request by IyadKandalaft**
### Proposed changes
One line change to the defaults template.yml to include the events_custom_options variable.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx/blob/master/CONTRIBUTING.md) document
-   [~] I have added Molecule tests that prove my fix is effective or that my feature works
I don't know if this is necessary.  The tests also don't include http_custom_options , so I was hesitant to add one for events_custom_options.  Please advise
-   [X] I have checked that all unit tests pass after adding my changes
All tests passed
-   [X] If required, I have updated necessary documentation (`defaults/main/` and `README.md`)
README.md references defaults/main/template.yml , which is what I've updated.

### CODE REVIEW

**Comment by alessfg** [comment]
Good catch! Ideally I'd like to eventually have tests for all Ansible templating parameters. I think for the purpose of this PR it's fine if you only add a test for `events_custom_options` (although I would not complain if you added tests for `http_custom_options` too) 😄

**Comment by IyadKandalaft** [comment]
LOL, I would love to add tests but I've never written molecule tests.  So if you bare with me, I can give it a shot.  I'll try to squeeze this in over the holidays if that's okay by you?

**Comment by alessfg** [comment]
Yup that's totally fine by me ;)

**Comment by alessfg** [comment]
Hiya @IyadKandalaft -- any updates on this?

**Comment by alessfg** [comment]
Any updates @IyadKandalaft?

**Comment by alessfg** [comment]
I ended up adding some molecule tests myself -- hope you don't mind!

**Pull request merged**
