### PR TITLE
Add multiple servers for reverse proxy template

### PR DESCRIPTION
**Pull request by clwluvw**
Make availability for adding multiple server blocks for Nginx HTTP config file.

### CODE REVIEW

**Comment by clwluvw** [comment]
I think the config for travis-ci should be change based on this pull request.

**Comment by alessfg** [comment]
Could you update the tests on your end? Otherwise Travis is going to fail.

**Comment by clwluvw** [comment]
Tests got fixed.

**Comment by alessfg** [comment]
Thanks! This is something that I've been wanting to fix/implement for a while. You got ahead of me 😜

I've made a couple changes to improve custom options support and will merge as soon as tests complete.

**Comment by clwluvw** [comment]
There was a syntax error in `default.conf.j2` line 151 in your last commit and I have used `commit --amend` to fixed it. :smile: 
Syntax error:
```
{% if item.value.servers[server].]custom_options ...
```

**Comment by alessfg** [comment]
Good catch! Between this and #192 that's two PRs in a row where I've made a typo/blunder of some sort! Will merge asap.

**Comment by clwluvw** [comment]
I've also fixed a bug in `default.conf.j2` file that `item.value.proxy_cache.proxy_cache_valid` was going to get from `item.value.reverse_proxy` that isn't available in this pull request.
There were also a bug on default vars were you have forgotten to put `proxy_cache_valid` after `proxy_cache` and there were a syntax error actually. :sweat_smile:

**Comment by alessfg** [comment]
Done! And yep I noticed the error, made a couple fixes and pushed them, but seems like the push didn't go through for whatever reason? Eh, nevermind, thanks for jumping on it!

**Pull request merged**
