### PR TITLE
Add support for nginx_version when compiling NGINX from source

### PR DESCRIPTION
**Pull request by MohamedLamineAllal**
Note: this is a draft

### Proposed changes

- solve issue https://github.com/nginxinc/ansible-role-nginx/issues/645

Before the change. The latest version is installed. And no ability to fix the version

### Checklist

Before creating a PR, run through this checklist and mark each as complete:

- [ x ] I have read the [`CONTRIBUTING`](https://github.com/nginxinc/ansible-role-nginx/blob/main/CONTRIBUTING.md) document.
- [ x ] I have added Molecule tests that prove my fix is effective or that my feature works.
- [ ] I have checked that any relevant Molecule tests pass after adding my changes.
- [ ] I have updated any relevant documentation ([`defaults/main/*.yml`](https://github.com/nginxinc/ansible-role-nginx/blob/main/defaults/main/), [`README.md`](https://github.com/nginxinc/ansible-role-nginx/blob/main/README.md) and [`CHANGELOG.md`](https://github.com/nginxinc/ansible-role-nginx/blob/main/CHANGELOG.md)).

# NOTE

- This is a draft. I didn't run tests. As i was limited in time to setup docker plugin on macos. I implemented the versioning for my own use case.
    (I guess github actions will run the tests)
    - If someone can take the draft, review it and run the tests. It would be nice.
    - Before that change latest version was installed only
- For the test i added. I'm not sure if it's supported to add nested folder. [✅ Already handled after review ✅]
    - I did copy the version test for from registry install
    - The how the test work is clear
    - I'm assuming nested folders are supported and molecule.yml is how a test is found
    - I'm not familiar with molecule
    - If what i did is not appropriate or doesn't work. The test is good. You can adjust it in the right structure.

### CODE REVIEW

**Comment by alessfg** [comment]
At first glance the changes look good!

Molecule does not support nested scenarios (folders) so you'd have to create a new scenario (e.g. `source-version`) and throw your tests in there. You'll also have to add the new scenario to the GH actions matrix 😁

**Comment by MohamedLamineAllal** [comment]
> At first glance the changes look good!
> 
> Molecule does not support nested scenarios (folders) so you'd have to create a new scenario (e.g. `source-version`) and throw your tests in there. You'll also have to add the new scenario to the GH actions matrix 😁

Changes applied as you suggested.

**Comment by MohamedLamineAllal** [comment]
The test did fail with `no space left in device`. Why is that?
image

- I wasn't using the exact test scenario as `source` scenario. Now i switched to use the exact same. With `specifying the version` as the only difference. And checking for the version (Note as well: the latest now is `1.25.2`  and the test does install `1.25.1`)

I noticed

```yml
platforms: # Oracle Linux 7 works in local tests but bugs out in GitHub actions for some undetermined reason
```

- Old test did include oracle
- `source` scenario does not include it
    - The new update follow `source` on that
    
- I did remove `- name: Check if NGINX is installed` check i included before. As it's not for when installing from source. I made that mistake before.

**Comment by MohamedLamineAllal** [comment]
- the version test, doesn't have to do anything with nginx open source!!

>   TASK [nginxinc.nginx : (AlmaLinux/Amazon Linux/CentOS/Oracle Linux/RHEL/Rocky Linux) Install NGINX] ***
  fatal: [rhel-9]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'ubi-9-baseos-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
  
Screenshot 2023-10-02 at 10 31 38 PM

Screenshot 2023-10-02 at 10 33 01 PM

**Review by alessfg — APPROVED** [review]

**Comment by alessfg** [comment]
Merged. Thanks for the PR!

**Pull request merged**
