### PR TITLE
Add `add_header` support for either `server` and `location` block

### PR DESCRIPTION
**Pull request by shokinn**
Add support for adding headers either in the server or in the location (either web_server or revers_proxy) block.

### CODE REVIEW

**Comment by shokinn** [comment]
Hey,
I'd like to ask where I should add the config parts to the test files. Is there a scheme or just add them to the fitting places?

**Comment by alessfg** [comment]
Hi @shokinn!

There's no scheme for test files, just add any new directives you want to test to the best fitting/logical place in the test playbooks.

Cheers,
Alessandro.

**Comment by shokinn** [comment]
Tests seems to be working :)

**Comment by gdzien** [comment]
Hello,

Your PR looks good, thank you very much for your contribution. However I would like to ask for tiny change just for clarity.
You use `#header_n:` in your example could you replace this string with `header_name:` so it will be more clear and understandable to people not as proficient in NGINX/Ansible language?

Thank you in advance,
Grzegorz

**Comment by shokinn** [comment]
Hi @gdzien,
done.
Hope it fits now :)

**Comment by gdzien** [comment]
It's perfect now. Thank you very much for your contribution. Merging.

**Pull request merged**
