### PR TITLE
Add RedHat prerequisites

### PR DESCRIPTION
**Pull request by jc36**
### Proposed changes
I use these tasks in my playbook for reverse proxy to kibana before using the role.

### Checklist
-   [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx/blob/master/CONTRIBUTING.md) document
-   [ ]  ~~I have added Molecule tests that prove my fix is effective or that my feature works~~
-   [x] I tried to add Molecule tests, but in docker containers selinux is disabled
-   [x] I have checked that all unit tests pass after adding my changes
-   [x] If required, I have updated necessary documentation (`defaults/main/` and `README.md`)

### CODE REVIEW

**Comment by magicalyak** [comment]
@jc36 I was planning to work on this soon, are you trying to do the same here? https://github.com/nginxinc/ansible-role-nginx/issues/247

**Comment by jc36** [comment]
@magicalyak I would be happy if this solves the problems that you describe in [#247 ](https://github.com/nginxinc/ansible-role-nginx/issues/247) issue. I only know that this helps in my case:
```
nginx_http_template:
  default:
    servers:
      server:
        server_name: _
        listen:
          listen_default:
            port: 80
            opts:
             - 'default_server'
        reverse_proxy:
          locations:
            backend:
              location: /
              proxy_pass: http://127.0.0.1:5601
              custom_options:
                # Allow access from Vagrant Host (only for local tests)
                - 'allow 192.168.33.1/32'
                # Deny access for everyone else
                - 'deny  all'
```
**httpd_can_network_connect** - allow httpd to connect to the network using TCP
**httpd_setrlimit** - allow httpd daemon to change system limits

**Comment by magicalyak** [comment]
My thought was using a flag (which I discussed with the maintainer on the side but you already seem to be thinking the same which is great!).
I'm trying to think of a test case that we can work with.

1) selinux enforcing
2) boolean that defaults to no (yes would handle selinux permissions) this preserves unexpected usage
3) set selinux httpd boolean
4) ports and firewalld? - wondering how far I go there?  Do we need to account for 8080 (status port) with seport?

**Comment by xTrekStorex** [comment]
> 4. ports and firewalld? - wondering how far I go there?  Do we need to account for 8080 (status port) with seport?

Thought I might just chime in even though I am not a RHEL/selinux user. 
If this role is going to enforce system security changes then they should be based on what is actually configured.
E.g. I use port 8000 for stub_status on all my deployments, since 8080 is usually bound by our local Tomcats or docker-proxy.

So adding a firewall rule for port 8080 by default wouldn't solve the issue for all deployments and is redundant in case another app is using port 8080 and thus has it already passed in firewall config.

The cleanest way IMHO would be to map a list of all configured listen ports in nginx_http_template + nginx_status_port and use that for firewalld etc.

**Comment by magicalyak** [comment]
Might need to do an on/off/custom option here.  Good feedback.

**Comment by alessfg** [comment]
Any updates on this PR? I'd be happy to merge what's here if we change the check from `ansible_selinux.status` to a role variable such as `nginx_selinux`. 

I'd rather have users have to explicitly state that they want to tweak selinux instead of automatically making some changes based on the system's current selinux state.

**Comment by magicalyak** [comment]
This PR does the same thing now
https://github.com/nginxinc/ansible-role-nginx/pull/272

**Comment by alessfg** [comment]
Closing this since #272 should have accomplished the same functionality. Feel free to reopen if that's not the case!

**Pull request closed without merging**
