### PR TITLE
[BUGFIX] Fixing missing list filter

### PR DESCRIPTION
**Pull request by JKetelaar**
Related to nginxinc/ansible-role-nginx-config#15

### Proposed changes
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

-   [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx/blob/master/CONTRIBUTING.md) document
-   [ ] I have added Molecule tests that prove my fix is effective or that my feature works
-   [ ] I have checked that all Molecule tests pass after adding my changes
-   [ ] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)

### CODE REVIEW

**Comment by alessfg** [comment]
As detailed in the README and the Changelog, I am not planning on working/merging NGINX config or NGINX Unit related issues in this role unless it's a major bugfix.

**Comment by JKetelaar** [comment]
Thanks for your response @alessfg. While I understand that not every merge request should be merged on both ends, this pull request is simply referring to the issue as this is how I came across the solution.
This pull request does fix an issue that has been introduced recently (read last 1-2 months) and only occurs when the given variable is not set.

**Comment by alessfg** [comment]
I'm still not entirely sure about merging this PR. You should be migrating your environment to use the NGINX config role for deleting previous configs. And if you set `nginx_cleanup_config` to `false` (which happens to be the default value), you should not encounter this issue.

I'll leave this PR open for the time being while I keep thinking about it. I might still end up merging it, but I don't want to make any promises.

**Comment by JKetelaar** [comment]
So would you suggest moving to the NGINX config role or stay onto this role? I tried to understand this from the README, but I'm not entirely sure what to do now.

**Comment by alessfg** [comment]
The idea would be to use this role to install NGINX, and then use the NGINX config role to handle anything related to NGINX configs.

**Comment by JKetelaar** [comment]
Aha that makes sense, thanks for explaining this! One last question if you don't mind; why does this role still have config then if it's actual purpose is solely for installation?

**Comment by alessfg** [comment]
Initially, everything was done in this role. I want to make sure that people have a reasonable amount of time to switch their config tasks to the new role before I eliminate it from this role.

**Comment by JKetelaar** [comment]
Thanks for the info! You might want to clarify this properly in the docs, as I didn't even know this role was "deprecated" in that sense.

**Comment by alessfg** [comment]
I've expanded on the README deprecation warning in #319 😄

**Comment by JKetelaar** [comment]
Great change, thanks for all the clarification and work @alessfg!

**Pull request closed without merging**
