### PR TITLE
Run logrotate only logrotate config changes

### PR DESCRIPTION
**Pull request by clwluvw**
### Proposed changes
Use notify handler to run logrotate if logrotate config changes.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

-   [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx/blob/master/CONTRIBUTING.md) document
-   [x] I have added Molecule tests that prove my fix is effective or that my feature works
-   [x] I have checked that all Molecule tests pass after adding my changes
-   [x] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)

### CODE REVIEW

**Comment by alessfg** [comment]
There's some issues with Travis atm. Not entirely sure if it's on their end or whether some package broke (I can't reproduce the issue myself so I'm going to go with the former).I'll rerun the tests when the issue gets fixed.

**Comment by clwluvw** [comment]
@alessfg Can this be removed with thie PR?

**Comment by alessfg** [comment]
Hm I would rather leave it there since the debug output tasks can also fail if NGINX isn't running already (which happens to be the case in some distros where the service doesn't get started upon installation of NGINX). Is there any particular reason why you'd like to see it removed?

**Comment by clwluvw** [comment]
@alessfg Not really just a warning that can be ignored I think
```
[WARNING]: flush_handlers task does not support when conditional
```

**Comment by alessfg** [comment]
Yep. That warning doesn't apply in this case.

**Comment by clwluvw** [comment]
According to https://github.com/nginxinc/ansible-role-nginx/pull/298#issuecomment-676538588 if this repo is going to deprecate, is there any reason there is no logrotate config in your mentioned repo?

**Comment by alessfg** [comment]
This repo won't deprecate. It's going to continue being used to install and setup NGINX, while NGINX config related tasks while move to another repo.

**Comment by clwluvw** [comment]
> This repo won't deprecate. It's going to continue being used to install and setup NGINX, while NGINX config related tasks while move to another repo.

@alessfg So this repo is just used for installing and the repo you mentioned is used to configure an installed nginx?
If yes can you please explain more why?

**Comment by alessfg** [comment]
Check https://github.com/nginxinc/ansible-role-nginx/pull/306 for a brief explanation as to why.

**Comment by clwluvw** [comment]
@alessfg Makes sense, thanks. So could you please check the CI why it fails again? :smiley:

**Comment by alessfg** [comment]
I cancelled the build to make #306 go faster. I'll rerun it once I merge that PR.

**Pull request merged**
