### PR TITLE
    Sanity test added

### PR DESCRIPTION
**Pull request by vbotka**
* Added sanity tests for FreeBSD and OpenBSD
    * Added variables nginx_*bsd_supported_packages and nginx_*bsd_installed_modules
    * FreeBSD default options correspond to FreeBSD port's tree default options

### CODE REVIEW

**Comment by vbotka** [comment]
Travis CI build failed with the message:
```
"You need to install \"jmespath\" prior to running json_query filter"
```
I've used "json_query". "json_query" a strong tool and it might be useful in other tasks too. Do you think it might be possible to install the required dependency (jmespath) on tested masters?

**Comment by alessfg** [comment]
I would rather avoid installing dependencies if it's possible. That being said, I'm not opposed to additional dependencies if they solve a specific use case. Although in this case it seems like you managed to get around the dependency requirement.

Re this PR, what's the exact purpose of it? Looking at the code it seems as if all it's doing is checking that some packages are present and whether NGINX is installed. In that case, and seeing as how I would not expect the new variables you introduced to be changed under most circumstances, maybe it would make sense to put them in the `vars` directory instead of `defaults`?

**Comment by vbotka** [comment]
> I would rather avoid installing dependencies if it's possible.

OK. Jmespath is not needed at the moment.

> Re this PR, what's the exact purpose of it?

The main purpose is to provide the structure to control the relation of installed packages or ports and installed modules. In this respect, the variables nginx_*bsd_supported_packages and nginx_*bsd_installed_modules keep the essential information.

> Looking at the code it seems as if all it's doing is checking that some packages are present and whether NGINX is installed. In that case, and seeing as how I would not expect the new variables you introduced to be changed under most circumstances, maybe it would make sense to put them in the `vars` directory instead of `defaults`?

I'd expect *bsd administrators to build custom packages and fit the mentioned variables.  This would help with the maintenance of heterogeneous architectures and would provide an option to control 3rd parties' *BSD packages. Putting it into vars (precedence 15.) instead of defaults (precedence 1.) does not make [sense](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable).

Instead, because of the maintenance (I think), it might be useful to create directory defaults/main and split the file main.yml. See [Allow loading dirs from role defaults/vars #36357](https://github.com/ansible/ansible/pull/36357).

I do not insist on this PR. It's a functionality/modularity/complexity trade-off. Such functionality might be implemented outside the role. It's really up to you if you want to have it in, or not. Feel free to reject it.

**Comment by alessfg** [comment]
I see. I'm not entirely sure that such functionality really fits within this role but I'll leave the PR open for the time being.

> Instead, because of the maintenance (I think), it might be useful to create directory defaults/main and split the file main.yml. See Allow loading dirs from role defaults/vars #36357.

Seeing the ever growing size of `defaults/main.yml` I would agree that it might be time to split the file into smaller functional files.

**Pull request closed without merging**
