### PR TITLE
Websocket support enabled for reverse proxy locations.

### PR DESCRIPTION
**Pull request by carlba**
https://www.nginx.com/blog/websocket-nginx

I couldn't really decide what was a good position of the websocket key so I just put it somewhere. I will ofcourse move it or change name of it based on the comments on this PR.

### CODE REVIEW

**Comment by carlba** [comment]
The travis error doesn't seem related to this change.

**Comment by carlba** [comment]
> Thanks for the PR @carlba! Can you update the README too?

Did I add it in the correct place? :)

**Comment by alessfg** [comment]
Agree @carlba! It's better to configure it per location block.

**Comment by carlba** [comment]
> Yeah you are right, it would be better to configure websocket support per location block instead of using the same setting for all locations.

Alright I moved it! :)

**Pull request merged**
