### PR TITLE
Advance SSL and proxy SSL settings

### PR DESCRIPTION
**Pull request by tallen116**
Here is some advance SSL and proxy SSL settings for stream and http reverse proxy blocks.  I believe these would make a great addition.

### CODE REVIEW

**Comment by alessfg** [comment]
Thanks for the PR @tallen116! I'll take a look as soon as you solve the merge conflicts :)

**Comment by tallen116** [comment]
Thank you.  I will work on the conflicts soon.

**Comment by tallen116** [comment]
Let me know if there is anything that you would like completed @alessfg

**Comment by tallen116** [comment]
SSL paths have been changed.  Let the merging begin!

**Comment by alessfg** [comment]
Hi @tallen116! Looks like you forgot to change the stream template variables! We'll merge this PR as soon as that's fixed 😝

**Comment by tallen116** [comment]
You got me.  It should be good now.

**Comment by gdzien** [comment]
Megred, thank you for your work on our 100th PR!

**Pull request merged**
