### PR TITLE
Add custom_options

### PR DESCRIPTION
**Pull request by changyy**
Thanks for providing the manageable nginx configuration files with `templates/http/default.conf.j2`. I tried to set the usage of the PHP-FPM, but the current template is not suitable.

I have added the `custom_options` for it:

```
{% if item.value.web_server.locations[location].custom_options is defined and item.value.web_server.locations[location].custom_options | length %}
{% for inline_option in item.value.web_server.locations[location].custom_options %}
        {{ inline_option }};
{% endfor %}
{% endif %}
```

Example:

```
  #- role: ansible-role-nginx
  - role: ansible-role-nginx-1
    become: yes

  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        listen:
          listen_localhost:
            port: 80
        server_name: localhost
        error_page: /usr/share/nginx/html
        autoindex: false
        web_server:
          locations:
            default:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: index.html
              autoindex: false
            php-fpm:
              location: ~ \.php$
              custom_options:
              - fastcgi_split_path_info ^(.+\.php)(/.+)$
              - fastcgi_pass unix:/var/run/php5-fpm.sock
              - fastcgi_index index.php
              - include fastcgi_params
              - fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name
          http_demo_conf: false
```

Result:

```
server {
    listen 80;
    server_name localhost;


    location / {
        root   /usr/share/nginx/html;
        index  index.html;

    }
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

    }
    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

### CODE REVIEW

**Comment by alessfg** [comment]
Thanks for the PR! This is something I've been meaning to tackle for a long time but never got around. Your PR is a good starting point, but it only covers custom options in http web server location blocks. 

Ideally, there should be a custom options parameter available in every NGINX context possible (`main`, `http`, `http_server`, `location` - both in proxy and web server scenarios, `stream`, etc...). Do you think you could you add a similar option to all these contexts? If you have any questions I can always help out.

Finally, it'd be great to have an example of the `custom_options` parameter on `defaults/main.yml` and the `README`, and add a working example to the test suite.

**Comment by alessfg** [comment]
Hiya!

Thanks for making the requested changes. Couple things:

1) Seems like the README and `defaults/main.yml` is missing some of the custom option directives you added to the main templates (e.g. there's no custom options for the main template)

2) The test file where you added the tests is a legacy test file that didn't get removed accidentally (whoops). Can you incorporate your example to `molecule/template_module/playbook.yml` instead? Adding the `php` location block you created to one of the already existing server blocks should work.

**Comment by changyy** [comment]
> Hiya!
> 
> Thanks for making the requested changes. Couple things:
> 
> 1. Seems like the README and `defaults/main.yml` is missing some of the custom option directives you added to the main templates (e.g. there's no custom options for the main template)
> 2. The test file where you added the tests is a legacy test file that didn't get removed accidentally (whoops). Can you incorporate your example to `molecule/template_module/playbook.yml` instead? Adding the `php` location block you created to one of the already existing server blocks should work.

OK! I have updated them.

**Comment by alessfg** [comment]
Thanks! I've made a couple final changes to bring everything up to speed (deleted the unused test file and made a couple changes to the custom options layout).

**Comment by changyy** [comment]
Thank you!

**Pull request merged**
