### PR TITLE
Allow auth basic to be added to global (server)

### PR DESCRIPTION
**Pull request by kutysam**
Was having an issue to make my entire site to have password protection as the template only provides 'location' level protection.

According to the official docs, we can enable http authentication on 'server' level: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

### CODE REVIEW

**Comment by kutysam** [comment]
side note: Since recent auth change additions are still in master branch and have not been made into a release yet to ansible galaxy, shall we rename `auth_basic_file `to `auth_basic_user_file` as the official key is the latter

**Comment by kutysam** [comment]
Could someone of admin power, please restart the CI build. It's failing not due to my code.

**Comment by alessfg** [comment]
Thanks for the PR @kutysam!

> shall we rename auth_basic_file to auth_basic_user_file as the official key is the latter

Yes we should, good catch!

> Could someone of admin power, please restart the CI build. It's failing not due to my code.

Only the `artful` builds are failing since Docker images for `artful` are no longer available. I'll try to get this updated asap.

One last thought - can you update `defaults/main.yml` too?

Cheers,
Alessandro.

**Comment by kutysam** [comment]
Done! Renamed and added to main.yml

**Comment by gdzien** [comment]
Thank you very much for your contribution!

**Pull request merged**
